### ISSUE TITLE
Profiling until run_steps=2^32 is feasible!

### ISSUE THREAD

**Issue by mahrud** [mggg/GerryChain#132]
I'm attempting to add some concurrency to the program. Michael suggested that I use `pytest` to profile the code first. Here is a profile of the `four_histograms.py` example:
![image](https://user-images.githubusercontent.com/3147718/42476246-2e7b5386-8382-11e8-92eb-7321e0d2839d.png)

My understanding is that the next iteration of chain (along with `is_valid`, if not `accept`) is independent of updates. Is that correct? If so, I think it shouldn't be too hard to sidestep GIL and run the updaters concurrently on other CPU cores. Any thoughts?

**Comment by mahrud** [comment]
I can't profile the same `four_histograms.py` example anymore due to this error:
```
  File "/.../rundmcmc/defaults.py", line 13, in <module>
    from rundmcmc.updaters import (Tally, boundary_nodes, county_splits, cut_edges,
ImportError: cannot import name 'polsby_popper'
```
But I made the profile of `rundmcmc.__main__.main` (with some changes so it's a test) with Pennsylvania data:
![image](https://user-images.githubusercontent.com/3147718/42511550-0572b29c-8407-11e8-8a0b-dd1ba94cb9ef.png)

You can remake this with:
```
pytest script.py --profile-svg
```
Where `script.py` has at least one function named like `test_blah()` and returns True or False.
Looks like `fast_connected` is the bottleneck now, which fortunately can actually be parallelized very easily!

**Comment by mahrud** [comment]
Thank you for fixing the examples! `single_flip_contiguous` worked also.

It seems to me like most time is spent in graph related functions and I'm
sure any C++ graph implementation worth its salt will have a decent amount
of concurrency, so I'm looking forward to seeing how much performance
<https://graph-tool.skewed.de/performance> improves with graph-tool.

Besides that, I think a good idea is to have `MarkovChain.__next__` only
directly call functions whose outputs are needed to compute the next
proposal or state. Everything else can be a made into method functions of
the state and the user can call them, like this:
```
data = []
for state in chain:
    state.auxillary_updates() # such as votes, seat shares, state scores,
etc.
    data.append(state.report()) # save something for later
```

I have an actual example here
<https://github.com/mahrud/RunDMCMC/commit/4877842e8d7183d90199154ce5cddc23f2458a9b#diff-540d2310bb896d1096d2d6fc5c8246cfR69>,
but it's a few days old. I'll rebase tonight and see if it helps at all.

**Comment by mahrud** [comment]
Thank you for fixing the examples! `single_flip_contiguous` worked also.

It seems to me like most time is spent in graph related functions and I'm
sure any C++ graph implementation worth its salt will have a decent amount
of concurrency, so I'm looking forward to seeing how much [performance](https://graph-tool.skewed.de/performance) improves with graph-tool.

Besides that, I think a good idea is to have `MarkovChain.__next__` only
directly call functions whose outputs are needed to compute the next
proposal or state. Everything else can be a made into method functions of
the state and the user can call them, like this:
```
data = []
for state in chain:
    state.auxillary_updates() # such as votes, seat shares, state scores,
etc.
    data.append(state.report()) # save something for later
```

I have an actual example [here](https://github.com/mahrud/RunDMCMC/commit/4877842e8d7183d90199154ce5cddc23f2458a9b#diff-540d2310bb896d1096d2d6fc5c8246cfR69),
but it's a few days old. I'll rebase tonight and see if it helps at all.

**Comment by rwbogl** [comment]
> Besides that, I think a good idea is to have MarkovChain.__next__ only
directly call functions whose outputs are needed to compute the next
proposal or state.

In theory, that's what the updater layer is supposed to do. You would only add updaters that were necessary for validation and acceptance, and other functions following the updater "API" could be used in the main loop like you mentioned.
