### ISSUE TITLE
Dynamic meta-graph variable

### ISSUE THREAD

**Issue by Untellable** [mggg/GerryChain#138]
At the moment the metagraph calculation accepts a chain rather than a partition and is hard to use within the chain. Could someone make it an optional updater or score in partition? I'd like to be able to access it within proposals for use in the laziness calculations but it's kindof a hassle right now and that seems like the best fix.

**Comment by rwbogl** [comment]
I'll take a look at this. The metagraph calculations (and other scores, maybe?) look a little clunky right now. They should probably be more modular.

**Comment by maxhully** [comment]
So one thing to keep in mind here is that the metagraph degree computation we're doing only applies to the single-flip proposal. For other proposals you'll have to provide a way to enumerate every possible flip that we should check for validity.

**Comment by rwbogl** [comment]
This feature was added in #141.

@maxhully's point is good. Perhaps the updater should be named to include the phrase "single flip" in there somewhere.

**Comment by rwbogl** [comment]
See #157 for a problem with this feature. After that's fixed I think we can close this.

**Comment by maxhully** [comment]
In #268 this is reimplemented just as a function to call for each partition in the chain.
