### ISSUE TITLE
JSON syntax error

### ISSUE THREAD

**Issue by rwbogl** [mggg/GerryChain#155]
When flips are saved as a JSON file, the JSON is ill-formed. I suspect that this is due to the homebrew JSON saving going on [here in `run.py`](https://github.com/gerrymandr/RunDMCMC/blob/7e5e29d841051ecf5b210450e60b4df5a81792e0/rundmcmc/run.py#L74).

If I had to guess, this could all be replaced by putting the flips into a list and calling `json.dumps()` on that list. JSON supports lists, after all, and the keys are just numbers in that homebrew saving anywhere.

(I don't yet have a minimum working example. If I can find/create one, I'll post it here.)

**Comment by drdeford** [comment]
Are the ones at the end of template_main.py better? That is the format the visualizations group/Alaska has been using, I think.

**Comment by rwbogl** [comment]
Yes, that's more-or-less how I imagined `run.py` being changed. I'll take a closer look later and see what I can do.
