### ISSUE TITLE
MetagraphDegree cyclic dependency

### ISSUE THREAD

**Issue by drdeford** [mggg/GerryChain#157]
In order to initialize MetagraphDegree you need the validator

In order to construct the validator you need the partition (UpperBound/within_percent...)

In order to construct the partition you need the updaters.

MetagraphDegree is an updater. 

(See template_main.py for an implementation of the cycle)

**Comment by rwbogl** [comment]
This is only a problem for validators that require computations related to the initial partition. "Independent" validators work fine, like [here](https://github.com/gerrymandr/RunDMCMC/blob/827747ec41d524ded7900f4f4fe775612ad53d2c/examples/metagraph_degree_updater.py).

Here's a hack-fix idea: Make a partition without the minimal updaters needed, compute the initial statistic, then make a new partition with MetagraphDegree (and other updaters) added.

**Comment by drdeford** [comment]
Yup, that is what is currently implemented in template_main.py - just wanted to raise awareness.

**Comment by maxhully** [comment]
Fixed this in #268
