### ISSUE TITLE
Replay a chain run from flips history

### ISSUE THREAD

**Issue by maxhully** [mggg/GerryChain#191]
I want to be able to capture the history of flips that occurred in my chain run, and then replay that chain run using those flips.

**Comment by drdeford** [comment]
I added a score for this so it can be written to the table. The current version of generate_ensembles makes use of this to make plots corresponding to the histogram data (bottom of the file).

**Comment by InnovativeInventor** [comment]
See [mggg/pcompress](https://github.com/mggg/pcompress).
