### ISSUE TITLE
Need a more permissive license

### ISSUE THREAD

**Issue by maxhully** [mggg/GerryChain#258]
Our current AGPL license is an obstacle for our friends in national laboratories and at Google. We need to replace it with a more permissive license so that they can use the library.

I'll go ahead and change AGPL to GPL, so that people aren't blocked from using GerryChain. Does anyone have any opinions on licenses?

**Comment by rwbogl** [comment]
I, like the rest of us I'm sure, have many opinions on licenses. Baring any other complications, the GPL seems like a good choice! Free and copyleft sounds about right for GerryChain.

Why were we using the AGPL anyway? I thought that it was mainly for network-facing applications.

**Comment by maxhully** [comment]
I don't know! I am not an expert on licenses.

**Comment by rwbogl** [comment]
>I don't know! I am not an expert on licenses.

Haha, that's a pretty good reason!

If anyone is curious, here's what [GNU has to say about the two](https://www.gnu.org/licenses/why-affero-gpl.en.html):

>Suppose you develop and release a free program under the ordinary GNU GPL. If developer D modifies the program and releases it, the GPL requires him to distribute his version under the GPL too. Thus, if you get a copy of his version, you are free to incorporate some or all of his changes into your own version.
>
>But suppose the program is mainly useful on servers. When D modifies the program, he might very likely run it on his own server and never release copies. Then you would never get a copy of the source code of his version, so you would never have the chance to include his changes in your version. You may not like that outcome.

I don't think this situation is relevant for us, but I could be wrong.

**Comment by zschutzman** [comment]
Here's Google's license info thingy https://opensource.google.com/docs/thirdparty/licenses/

At Google at least the GPL issue is that the license requires including the GerryChain source along with their derivative, so they can't ship a product based on it because it doesn't conform to their standards.  This may or may not be how you want it to be.

**Comment by maxhully** [comment]
We should definitely keep talking about this, but we've addressed the immediate issue in #259 , so I'll close this for now.

**Comment by mrzv** [comment]
Any reason not to switch to MIT/BSD?

GPL is a problem for the national labs, not that I can imagine anyone working on this project as part of their national lab day job.

**Comment by ljwolf** [comment]
second on the MIT/BSD question. The scientific python stack tends to MIT/BSD, kind of like how the R stack tends to GPL. 

Most of your dependencies are MIT:
- [pandas](https://github.com/pandas-dev/pandas/blob/master/LICENSE) (BSD 3-clause)
- [matplotlib](https://matplotlib.org/users/license.html) (PSF, like BSD)
- [shapely](https://github.com/Toblerity/Shapely/blob/master/LICENSE.txt) (BSD 3-clause)
- [geopandas](https://github.com/geopandas/geopandas/blob/master/LICENSE.txt) (BSD 3-clause)
- [networkx](https://networkx.github.io/documentation/networkx-1.10/reference/legal.html) (BSD 3-clause)

**Comment by maxhully** [comment]
OK, how about BSD 3-clause?

**Comment by mrzv** [comment]
I think BSD 3-clause is great.
