### ISSUE TITLE
Include conda installation instructions and common problems

### ISSUE THREAD

**Issue by maxhully** [mggg/GerryChain#295]
We should now tell people to install with `conda`. We should also give some troubleshooting tips. Two that I know are:
- How to set the `PROJ_LIB` and `GDAL_DATA` environment variables if you are seeing errors about them
- Try installing everything from the conda-forge channel (no defaults) if things get weird

**Comment by msarahan** [comment]
current instructions recommend conda-forge channel: https://github.com/mggg/GerryChain#using-conda-recommended - I think this issue can be closed, but I no longer have the authority to do so.
