### ISSUE TITLE
Annealing in proposals and accepts

### ISSUE THREAD

**Issue by drdeford** [mggg/GerryChain#302]
It is a little awkward to implement annealing in our current proposal/acceptance setup. Like the extra parameters for the ReCom walks, we could use partial to pass the step number to the proposal (since the partition class doesn't track it). Alternatively, we could construct multiple, sequential Markov chain objects with different proposals or ?

**Comment by maxhully** [comment]
Hmmm... Maybe we should pass the step number? Or subclass MarkovChain to create an AnnealingMarkovChain or something like that that does pass the step number?

**Comment by drdeford** [comment]
I'm testing both the partial version and the updater version now. The updater is simple and seems to work well: 
![cuts2_40_1pop](https://user-images.githubusercontent.com/29463610/57466680-1dd51f00-724f-11e9-99df-deb933aa4b3e.png)
![end_40_1pop](https://user-images.githubusercontent.com/29463610/57466690-23326980-724f-11e9-9ba1-cb1935fe46ad.png)
![end2_40_1pop](https://user-images.githubusercontent.com/29463610/57466694-24639680-724f-11e9-87d5-3c0b5560b0b2.png)
![flip2_40_1pop](https://user-images.githubusercontent.com/29463610/57466702-288fb400-724f-11e9-89d8-5610d6d9fcfa.png)
![wca2_40_1pop](https://user-images.githubusercontent.com/29463610/57466715-2b8aa480-724f-11e9-989d-4373532d8be3.png)

**Comment by drdeford** [comment]
Turns out to be super easy to add an updater for this, which is something we should be encouraging people to do anyway.

**Comment by drdeford** [comment]
Closing since we now have plenty of examples with the updater version.
