### ISSUE TITLE
pop_target not updated in recursive_tree_part()

### ISSUE THREAD

**Issue by pjrule** [mggg/GerryChain#312]
I've been using `recursive_tree_part()` to split North Dakota's Census VTDs into 10 districts with an epsilon of 15%. With a population target of 67259.1, I've seen many runs where the first 9 districts (and more generally, the first _n_-1 districts) are allocated with populations below the target, resulting in the leftover voters being stuffed into the _n_-th district. Here are the populations from an example run:
```
   {0: 62966,
    1: 73140,
    2: 58006,
    3: 57653,
    4: 68164,
    5: 68149,
    6: 63184,
    7: 63916,
    8: 57318,
    9: 100095}
```

This seems to partially relate to the fact that `pop_target` is not dynamically updated as the graph is split. The code notes this:
https://github.com/mggg/GerryChain/blob/cf09999a1281b457e07d901b4b082cb189bb6936/gerrychain/tree.py#L217

@maxhully I'd be happy to submit a PR to fix this if we think it's a notable issue. Let's chat. :)

**Comment by maxhully** [comment]
Closed by #317 !
