### ISSUE TITLE
Graph.from_geodataframe() doesn't add column data

### ISSUE THREAD

**Issue by drdeford** [mggg/GerryChain#322]
Unlike .from_file there isn't a separate call to add data when you use from_geodataframe directly. Indeed, .from_file calls add data immediately after building the graph object with from_geodataframe. 

Is there a good reason to not have from_geodataframe take the cols_to_add argument and do everything at once?

**Comment by zschutzman** [comment]
I can't think of a good reason, especially because `from_file` calls `from_geodataframe`.

This seems like a reasonable thing to implement if someone wants to do the pull request, or I can do it when I get back from China.

**Comment by drdeford** [comment]
I'll take care of it.

**Comment by drdeford** [comment]
Solved by @zschutzman  in PR #324

**Comment by zschutzman** [comment]
Fixed in #324.
