### ISSUE TITLE
`gerrychain.Partition(..., assignment = None)` fails

### ISSUE THREAD

**Issue by leehach** [mggg/GerryChain#326]
The `gerrychain.Partition()` method has an `assignment` parameter which represents the district each node is assigned to. This can be used to set the initial plan for a chain run. According to the docs:

> Dictionary assigning nodes to districts. If None, initialized to assign all nodes to district 0.

However, running with `assignment = None` generates the following error:

```
TypeError: Assignment must be a dict or a node attribute key
```

**Comment by zschutzman** [comment]
That's a good catch! There's currently no default behavior for not providing an assignment. I've opened PR #329 to resolve this.
