### ISSUE TITLE
Can't create graph if data frame index set to identifier

### ISSUE THREAD

**Issue by leehach** [mggg/GerryChain#327]
I want a graph where the nodes use the geographic identifiers as node labels, rather than the data frame index. Trying to run the following code from the [Working with Partitions](https://gerrychain.readthedocs.io/en/latest/user/partitions.html) documentation:

```python
df = geopandas.read_file("https://github.com/mggg-states/PA-shapefiles/raw/master/PA/PA_VTD.zip")
df.set_index("GEOID10", inplace=True)
graph = Graph.from_geodataframe(df)
graph.add_data(df)
```

The call to `Graph.from_geodataframe` fails with the following error (abbreviated traceback):

```
  File "/home/lee/miniconda3/envs/vrdi2019/lib/python3.7/site-packages/gerrychain/graph/adjacency.py", line 38, in <genexpr>
    p.id for p in possible if (not p.is_empty) and p.id != geometry.id

AttributeError: 'Polygon' object has no attribute 'id'
```

# Failed Workaround

I skipped line 2 and reassigned the node labels as follows:

```python
import networkx as nx

mapping = dict(zip(list(df.index), list(df["GEOID10"])))
graph = nx.relabel_nodes(graph, mapping, copy = False)
```

This works. However, after creating an initial partition, the call to `MarkovChain` fails:

```python
election = Election("SEN12", {"Dem": "USS12D", "Rep": "USS12R"})

initial_partition = Partition(
    graph,
    assignment = "CD_2011",
    updaters = {
        "cut_edges": cut_edges,
        "population": Tally("TOTPOP", alias="population"),
        "SEN12": election
    }
)

chain = MarkovChain(
    proposal=propose_random_flip,
    constraints=[single_flip_contiguous],
    accept=always_accept,
    initial_state=initial_partition,
    total_steps=100
)
```

```
Traceback (most recent call last):

  File "<ipython-input-8-7aff1509138f>", line 6, in <module>
    total_steps=100

  File "/home/lee/miniconda3/envs/vrdi2019/lib/python3.7/site-packages/gerrychain/chain.py", line 47, in __init__
    raise ValueError(message)

ValueError: The given initial_state is not valid according is_valid. The failed constraints were: single_flip_contiguous
```

# Successful Workaround

Complete chain run and merge partitions by index (instead of GEOID) back onto original GeoDataFrame.

**Comment by zschutzman** [comment]
I noticed that the URL for the shapefile in the docs is out-of-date.  I'll see if I can figure out how to do a pull request for that.  

Using the URL in your stub, I get a 404 error. Using the following one,

```
df = geopandas.read_file("https://github.com/mggg-states/PA-shapefiles/raw/master/PA_VTDs.zip")
df.set_index("GEOID10", inplace=True)
graph = Graph.from_geodataframe(df)
```
it properly constructs the graph and I can't reproduce this error.

**Comment by leehach** [comment]
My bad. I altered the GEOID and ended up with something nonunique. `Graph.from_geodataframe` works fine on the original data and other datasets I tested with unique nodelabels.
