### ISSUE TITLE
 TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by amanbhala** [mggg/GerryChain#332]
From the quickstart page, I was trying to run the below example code in the jupyter notebook 

```
from gerrychain import Graph, Partition, Election
from gerrychain.updaters import Tally, cut_edges

graph = Graph.from_json("./PA_VTDs.json")

election = Election("SEN12", {"Dem": "USS12D", "Rep": "USS12R"})

initial_partition = Partition(
    graph,
    assignment="CD_2011",
    updaters={
        "cut_edges": cut_edges,
        "population": Tally("TOTPOP", alias="population"),
        "SEN12": election
    }
)
```

but it gave me the following error: 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-51-783972181c81> in <module>()
----> 1 from gerrychain import Graph, Partition, Election
      2 from gerrychain.updaters import Tally, cut_edges
      3 
      4 graph = Graph.from_json("./PA_VTDs.json")
      5 

/usr/local/lib/python2.7/dist-packages/gerrychain/__init__.py in <module>()
      1 from ._version import get_versions
----> 2 from .chain import MarkovChain
      3 from .graph import Graph
      4 from .partition import GeographicPartition, Partition
      5 from .updaters.election import Election

/usr/local/lib/python2.7/dist-packages/gerrychain/chain.py in <module>()
----> 1 from .constraints import Validator
      2 
      3 
      4 class MarkovChain:
      5     """

/usr/local/lib/python2.7/dist-packages/gerrychain/constraints/__init__.py in <module>()
     45                           no_worse_L1_reciprocal_polsby_popper,
     46                           no_worse_L_minus_1_polsby_popper)
---> 47 from .contiguity import (contiguous, contiguous_bfs, no_more_discontiguous,
     48                          single_flip_contiguous)
     49 from .validity import (Validator, districts_within_tolerance,

/usr/local/lib/python2.7/dist-packages/gerrychain/constraints/contiguity.py in <module>()
      4 import networkx as nx
      5 
----> 6 from ..random import random
      7 from .bounds import SelfConfiguringLowerBound
      8 

/usr/local/lib/python2.7/dist-packages/gerrychain/random.py in <module>()
      3 
      4 seed = os.environ.get("GERRYCHAIN_RANDOM_SEED", 2018)
----> 5 random.seed(seed)

TypeError: 'int' object is not callable

```
It is probably because of naming issue in random.py file but cannot figure out the exact issue, please help:
Contents of random.py file are:
```import os
import random

seed = os.environ.get("GERRYCHAIN_RANDOM_SEED", 2018)
random.seed(seed)
```

**Comment by apizzimenti** [comment]
Hi @amanbhala! I recreated your environment and ran a few tests. You're right about it being a naming issue – it's an instance of the [name-shadowing trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap). However, [this issue was resolved](https://bugs.python.org/issue22172) with the release of Python 3.4, so if you install a different version of Python ([version 3.6.5 or above](https://www.python.org/downloads/release/python-365/)) and use *that* for your GerryChain work, you should have no problems.

**Comment by amanbhala** [comment]
I am interested in working on the project Parallelization in Gerrychain as a part of Google Summer of Code, 2020. I am working on making a draft proposal for the project.Please let me know the expectations that the organization has from a student and preferable technologies/libraries that you would like me to use.
Thanks.

**Comment by apizzimenti** [comment]
Make sure to carefully read the guidelines on the [MGGG's GSoC page](http://bit.ly/gsoc-mggg) – if you have any more questions, send them to mggg-gsoc@gmail.com.

**Comment by amanbhala** [comment]
I ran the tool successfully and have gone through the code and now have an understanding of the workflow of the tool.I have find out few functions that I think can be parallelized.Some of them are mentioned below:
1. validator function in gerrychain.constraints.Validity as multiple processes can be created where each process can validate for a constraint parallely.
2. contiguous_bfs function in gerrychain.constraints.contiguity as bfs on each node can be represented as a single process and then those processes can work parallely.
3. polsby_popper function in gerrychain.metrics.comapactness as polsby pepper compactness scores for each district can be done as a process and these processes can work parallely.
4. join function in Gerrychain.graph.graph like when in a database when we want to get or put huge number of entries then we can create parallel processes which can work parallely and then the result of each process can be comibend.
5. invalid_geometries function Gerrychain.graph.geo .
Please let me know if I am thinking in the right direction or guide me if I'm wrong.
