### ISSUE TITLE
County splits example added to documentation

### ISSUE THREAD

**Issue by hjohns12** [mggg/GerryChain#334]
I want to implement the `refuse_new_splits` function from the `county_splits` definition and haven't been able to get it working. Could you add an example to the documentation where you add a constraint to minimize the number of county splits? Thanks so much in advance!

**Comment by InnovativeInventor** [comment]
> I want to implement the `refuse_new_splits` function from the `county_splits` definition and haven't been able to get it working. Could you add an example to the documentation where you add a constraint to minimize the number of county splits? Thanks so much in advance!

I think you should be able to parameterize the closure by passing an attribute on the dual graph (like `COUNTYFP20`) that indicates which county the node is in. This should produce an acceptance function that can be used like so:
```python
MarkovChain(
    proposal = proposal,
    constraints = [constraint],
    accept = refuse_new_splits("COUNTYFP20"),
    initial_state = seed_partition,
    total_steps = steps
)
```

However, depending on your use-case, you may want to use one of our county-aware variants of ReCom. Feel free to re-open if you have any other questions.
