### ISSUE TITLE
Conflicting population balance constraints

### ISSUE THREAD

**Issue by AtlasCommaJ** [mggg/GerryChain#353]
The population balance percentage can be set in two places.

in the recom proposal:
[`def recom(partition, pop_col, pop_target, epsilon, node_repeats=1, method=bipartition_tree):`](https://github.com/mggg/GerryChain/blob/01b8801877498f87d1b9968415bc7c2439f448c0/gerrychain/proposals/tree_proposals.py#L11)

and as a constraint:
[`def within_percent_of_ideal_population(initial_partition, percent=0.01, pop_key="population"):`](https://github.com/mggg/GerryChain/blob/01b8801877498f87d1b9968415bc7c2439f448c0/gerrychain/constraints/validity.py#L52)

This allows you to set a coarse value for the constraint, perhaps to let an initial partition pass through, but then enforce a stricter value later, which can cause the chain to stall. You can replicate this behavior in an extreme case: set the first to 0.0001 and the population to 0.99, then try to run a chain. It should start without warnings, but never finish an iteration.

**Comment by AtlasCommaJ** [comment]
Avenues of fixing the issue:
-ensure the initial partition is within the deviation specified by the recom proposal, as the constraint does
-throw a warning if these two values are different

**Comment by peterrrock2** [comment]
Hey! Thank you for bringing this to our attention! This is an intended behavior for our package. The reason for having two different places to set the population constraints -- in the drawing of the tree and the acceptance function -- is that placing a constraint in each of these locations does slightly different things to the distribution that you are targeting, and it is up to the user to determine which constraint is appropriate for their problem set (or if both are appropriate!). However, in practice, the stricter population bound should always be obeyed for any accepted proposed partition. We have also recently added some functionality to help with the sticking problem. For more information, please see [https://gerrychain.readthedocs.io/en/latest/user/recom/#what-to-do-if-the-chain-gets-stuck](https://gerrychain.readthedocs.io/en/latest/user/recom/#what-to-do-if-the-chain-gets-stuck)
