### ISSUE TITLE
Compatibility issue with shapely 2.x

### ISSUE THREAD

**Issue by KrisTapp** [mggg/GerryChain#408]
When I installed gerrychain with conda, the environment solver forced an upgrade from shapely 1.x to 2.x.  But yet gerrychain seems to have incompatibilities with shapely 2.x.   

For example, Graph.from_file caused errors for shapely 2.0, while in shapely 1.85, it only results in this message: "ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0"

**Comment by peterrrock2** [comment]
This should be fixed in the latest release. We have deprecated support for conda-forge, so we are asking everyone to install things using pip. Let me know if you have any more issues with this!
