### ISSUE TITLE
Code from conda install doesn't match latest GitHub code

### ISSUE THREAD

**Issue by tratliff** [mggg/GerryChain#412]
There are a few files in the gerrychain/graph/ subdirectory that have been updated on GitHub, but conda installs the older versions. Specifically, adjacency.py and graph.py are old, but there may be others that I haven't come across yet. 

I think the errors I'm seeing may be related to the ones KrisTapp reported in March concerning shapley 2.x.

**Comment by pjrule** [comment]
@tratliff This is a known issue—we're about to deprecate the Conda distribution. We recommend installing via pip (`pip install gerrychain`) instead. Sorry for the trouble! :)

**Comment by tratliff** [comment]
Thanks! I'll take a look at pip.
